name: Run Python script

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        python: ["3.10"]

    env:  # Set environment variables for all steps in this job
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      REPO: ${{ secrets.REPO }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Use PR number
        run: echo "PR number is $PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
      - name: Use secrets
        run: echo "API token is ${{ secrets.API_TOKEN }}"
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO: ${{ secrets.REPO }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          git config --global user.email "SidekickPro@ai"
          git config --global user.name "SidekickPro"
      - name: Run SidekickPro
        # Run tox using the version of Python in `PATH`
        run: python demo.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO: ${{ secrets.REPO }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
      - name: Apply patch
        # Run tox using the version of Python in `PATH`
        run: |
         git checkout -b kp/test-pragain
         cat demo.py
         rm file.patch
         git commit --allow-empty-message -am "address comments"
         git push --set-upstream origin kp/test-pragain
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}