name: Run Python script

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        python: ["3.10"]

    env:  # Set environment variables for all steps in this job
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      REPO: ${{ secrets.REPO }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Use secrets
        run: echo "API token is ${{ secrets.API_TOKEN }}"
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO: ${{ secrets.REPO }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run SidekickPro
        # Run tox using the version of Python in `PATH`
        run: python demo.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO: ${{ secrets.REPO }}