name: Run Python script

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # Set environment variables for all steps in this job
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Pull Python Docker image
      run: docker pull python:3.8

    - name: Create Docker volume
      run: docker volume create myvol

    - name: Install dependencies
      run: |
        docker run --rm -v myvol:/app -v ${{ github.workspace }}:/app -w /app python:3.8 pip install -r requirements.txt

    - name: Run demo.py
      run: |
        docker run --rm -v myvol:/app -v ${{ github.workspace }}:/app -w /app python:3.8 python demo.py